lang:
  prefix: "&r[&b&lUn&6&lseeable&r]"
  nonconsole: "%prefix You need to be a &6&lplayer&r to do this."
  nopermissions: "%prefix You do not have permissions to do this."
  nocmdingame: "%prefix You cannot use '&d$1&r' whilst ingame."
  suggest: "%prefix Please use &d$1."
  mapnotfound: "%prefix Map '$1' could not be found. Do /us list"
  mapinuse: "%prefix Map '$1' already exists."
  validnumber: "%prefix $1 needs to be a valid number."
  lesstwo: "%prefix $1 cannot be less than 2."
  selectwe: "%prefix Please select something using WorldEdit."
  cuboidwe: "%prefix Worth a try but selections need to be cuboid."
  mapcreate: "%prefix Successfully created map '$1'!"
  spawnadd: "%prefix Spawn Point added to map '$1' (currently $2)"
  spawnpowerup: "%prefix Powerup Point added to map '$1' (currently $2)"
  spawnfirework: "%prefix Firework Point added to map '$1' (currently $2)"
  spawnlose: "%prefix Loser spawn set for '$1'"
  spawnwin: "%prefix Winner spawn set for '$1'"
  spawnspectate: "%prefix Spectator Spawn set for '$1'"
  clearspawn: "%prefix All spawn points have been cleared for map '$1'"
  clearpowerup: "%prefix All powerup points have been cleared for map '$1'"
  clearfirework: "%prefix All firework points have been cleared for map '$1'"
  nomapsready: "%prefix &7No maps are ready to be played."
  mapnotsetup: "%prefix Map '$1' not setup properly."
  mapremove: "%prefix Successfully removed map '$1'."
  nogamestarted: "%prefix No game has started."
  gamealreadystopped: "%prefix Game already stopped."
  gamestopsuccess: "%prefix Game Stopped Successfully."
  gamestartsuccess: "%prefix Game Started Successfully."
  startin: "%prefix Game Starting in $1 seconds."
  startinfast: "%prefix Game Starting in $1!"
  endin: "%prefix Teleporting you back in $1 seconds."
  gamestart: "%prefix Game Started."
  spawn: "%prefix You have been spawned."
  fullroom: "%prefix Sorry, room is full."
  alreadyingame: "%prefix You are already ingame."
  queue: "%prefix Successfully joined the queue for '&a&l$1&r'."
  gamestillprogress: "%prefix Game still in progress."
  stop: "%prefix Game Abruptly Stopped. We are sorry for the inconvenience."
  forcestart: "%prefix The game was force started by $1"
  leave: "%prefix you left the Game."
  joinqueueother: "%prefix $1 Joined the Queue."
  gamestarting: "%prefix $1 A game is starting in map '$1' with $2 players and $3 places left. Do &d/us join &rto join."
  gamewin: "%prefix You won with $1 kills in map $2 and you won $3 moneyz."
  gametry: "%prefix You participated with $1 kills in map $2 and Lewis da god thinks you deserve $3 moneyz for trying."
  killed: "%prefix You got killed by $1"
  kill: "%prefix Congratz you killed $1 who has $2 kills and you now have $3 kills out of the $4"
  killbroadcast: "%prefix $1 killed $2 and now has $3 out of $4 kills"
  killtitle: "KILL"
  killsubtitle: "KILLSUBTITLE"
  deathtitle: "DEATH"
  deathsubtitle: "DEATHSUBTITLE"
  chooseamap: "Choose a map ($1)"
  mapicon: "WOOL"
  maptitle: "&a&l$1"
  noint: "%prefix '$1' is not a valid Number"
  propertyupdate: "%prefix '$1' updated to '$2' for '$3'."
  sign: "&r[&b&lUn&6&lseeable&r]"
allowed_commands:
  - usa
  - us
  - msg
  - reply
  - r
  - tell